### PR TITLE
added reactiveui example

### PR DESCRIPTION
**Pull request by fswadling**

### CODE REVIEW

**Comment by fswadling** [comment]
I have no idea why this is giving me problems. it builds fine on my branch and my pc

**Comment by sclarke81** [comment]
I only set the Appveyor build up to restore NuGet packages if they've been referenced using package references. We could change the build setup, but my preference would be to use package references anyway.

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fswadling** [comment]
Yeah, i'm going to need some help with the project setup, i'm in a bit of a mess with these Package references.

**Comment by sclarke81** [comment]
Try removing all of the package references and just adding this one:

`<PackageReference Include="reactiveui" Version="7.4.0" />`

Also remove packages.config and the include for it.

**Comment by fswadling** [comment]
Yep still not working

**Comment by fswadling** [comment]
alright, thats working

**Pull request merged**
